name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      EMSCRIPTEN_VERSION: '3.1.64'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt install -y ninja-build

      - name: Install emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk
          cd emsdk
          ./emsdk install ${{ env.EMSCRIPTEN_VERSION }}
          ./emsdk activate ${{ env.EMSCRIPTEN_VERSION }}

      - name: Build
        run: |
          . emsdk/emsdk_env.sh
          python scripts/fmt.py
          python scripts/iso-codes.py
          python scripts/json.py
          python scripts/json-c.py
          python scripts/marisa.py
          python scripts/libexpat.py
          python scripts/libthai.py
          python scripts/libxkbcommon.py
          python scripts/xkeyboard-config.py

      - name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            build/*.tar.bz2
